# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package jacoco:report --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3


      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sourcecodeanalyzer
          path: sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar

  after_success:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download sourcecodeanalyzer jar
        uses: actions/download-artifact@v3
        with:
          name: sourcecodeanalyzer
          path: sourcecodeanalyzer/target/

      - name: End-to-end run of the sourcecodeanalyzer module
        run: java -jar sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/test/resources/TestClass.java regex local output_metrics_file csv

      - name: Upload metrics file
        uses: actions/upload-artifact@v3
        with:
          name: output_metrics_file
          path: output_metrics_file.csv


  verify:
    needs: after_success
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download metrics file
        uses: actions/download-artifact@v3
        with:
          name: output_metrics_file


      - name: Compare metrics
        run: diff output_metrics_file.csv metrics_results.csv